WCS\WildExchangeBundle\Entity\Ecole:
    type: entity
    table: null
    repositoryClass: WCS\WildExchangeBundle\Repository\EcoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        ville:
            type: string
            length: 255
            column: Ville
    lifecycleCallbacks: {  }
