wcs_wild_exchange:
    resource: "@WCSWildExchangeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path:     /connexion
    defaults: { _controller: WCSWildExchangeBundle:Default:connexion }
