wcs_wild_exchange:
    resource: "@WCSWildExchangeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/


logout:
    path: /
    defaults: { _controller: WCSWildExchangeBundle:Default:Redirect }

logout:
    path: /logout
    defaults: { _controller: WCSWildExchangeBundle:Security:logout }
