# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:


    encoders:
        WCS\WildExchangeBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        our_db_provider:
            entity:
                class: WCSWildExchangeBundle:Utilisateur
                property: pseudo


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: our_db_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: connectionpage
                check_path: login
                success_handler: redirect.after.login
                remember_me: true
            logout:
                path:   /logout
                success_handler: redirect.after.logout
                invalidate_session: false

    access_control:
        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }