# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  # [...] Vos autres services

  redirect.after.login:
    class: WCS\WildExchangeBundle\Redirection\LoginRedirection
    arguments: [@security.context, @router, @session, @doctrine.orm.entity_manager]

  redirect.after.logout:
    class: WCS\WildExchangeBundle\Redirection\LogoutRedirection
    arguments: [@security.context, @router, @session]

  salavert.twig.time_ago:
    class: Salavert\Twig\Extension\TimeAgoExtension
    arguments: ["@translator"]
    tags:
        - { name: twig.extension }

  app.locale_listener:
    class: WCS\WildExchangeBundle\EventListener\LocaleListener
    arguments: ['%kernel.default_locale%']
    tags:
        - { name: kernel.event_subscriber }

