<?php

namespace WCS\WildExchangeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocsOffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocsOffRepository extends EntityRepository
{
}
