<?php

namespace WCS\WildExchangeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
    public function findAllSortedByVotes($tagid = null)
    {
        $querry =  $this->createQueryBuilder('a')
            ->select('COUNT(u) AS HIDDEN nbrVotes', 'a')
            ->leftJoin('a.votes', 'u')
            ->orderBy('nbrVotes', 'DESC')
            ->groupBy('a');

        if ($tagid){
            $querry
                ->where(':tagid MEMBER OF a.tags')
                ->setParameter("tagid", 1);

        }

        return $querry->getQuery()->getResult();

    }
}
