<?php

namespace Proxies\__CG__\WCS\WildExchangeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \WCS\WildExchangeBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'pseudo', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'motDePasse', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'interet', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'github', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'facebook', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'twitter', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'linkedin', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'avatarurl', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'dateInscription', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'dateConnexion', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'idrang', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'ecole', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'questions');
        }

        return array('__isInitialized__', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'pseudo', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'motDePasse', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'interet', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'github', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'facebook', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'twitter', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'linkedin', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'avatarurl', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'dateInscription', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'dateConnexion', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'idrang', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'ecole', '' . "\0" . 'WCS\\WildExchangeBundle\\Entity\\Utilisateur' . "\0" . 'questions');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', array($pseudo));

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', array());

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotDePasse($motDePasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotDePasse', array($motDePasse));

        return parent::setMotDePasse($motDePasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotDePasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotDePasse', array());

        return parent::getMotDePasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setInteret($interet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInteret', array($interet));

        return parent::setInteret($interet);
    }

    /**
     * {@inheritDoc}
     */
    public function getInteret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInteret', array());

        return parent::getInteret();
    }

    /**
     * {@inheritDoc}
     */
    public function setGithub($github)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGithub', array($github));

        return parent::setGithub($github);
    }

    /**
     * {@inheritDoc}
     */
    public function getGithub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGithub', array());

        return parent::getGithub();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedin($linkedin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', array($linkedin));

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', array());

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatarurl($avatarurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatarurl', array($avatarurl));

        return parent::setAvatarurl($avatarurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatarurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatarurl', array());

        return parent::getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscription($dateInscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscription', array($dateInscription));

        return parent::setDateInscription($dateInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscription', array());

        return parent::getDateInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateConnexion($dateConnexion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateConnexion', array($dateConnexion));

        return parent::setDateConnexion($dateConnexion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateConnexion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateConnexion', array());

        return parent::getDateConnexion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrang($idrang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrang', array($idrang));

        return parent::setIdrang($idrang);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrang', array());

        return parent::getIdrang();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdecole($idecole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdecole', array($idecole));

        return parent::setIdecole($idecole);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdecole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdecole', array());

        return parent::getIdecole();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcole(\WCS\WildExchangeBundle\Entity\Ecole $ecole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcole', array($ecole));

        return parent::setEcole($ecole);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcole', array());

        return parent::getEcole();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuestion(\WCS\WildExchangeBundle\Entity\Questions $questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuestion', array($questions));

        return parent::addQuestion($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuestion(\WCS\WildExchangeBundle\Entity\Questions $questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuestion', array($questions));

        return parent::removeQuestion($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', array());

        return parent::getQuestions();
    }

}
