homepage:
    path:     /
    defaults: { _controller: WCSWildExchangeBundle:Default:index }

connectionpage:
    path:     /connexion
    defaults: { _controller: WCSWildExchangeBundle:Security:connexion }

login:
    path:     /login
    defaults: { _controller: WCSWildExchangeBundle:Security:login }

inscriptionpage:
    path:     /inscription
    defaults: {  _controller: WCSWildExchangeBundle:Registration:register }

forgetpage:
    path:    /forget
    defaults: {  _controller: WCSWildExchangeBundle:Registration:forget }

tagspage:
    path:     /tags
    defaults: {  _controller: WCSWildExchangeBundle:Default:tags }

questionpage:
    path:     /questions/{tag}
    defaults: {  _controller: WCSWildExchangeBundle:Default:questions }

ajoutpage:
        path:     /ajout/{tag}
        defaults: {  _controller: WCSWildExchangeBundle:Question:ajout }

reponsepage:
        path:     /reponses/{id}
        defaults: {  _controller: WCSWildExchangeBundle:Default:reponses }

dashboardpage:
        path:     /dashboard
        defaults: {  _controller: WCSWildExchangeBundle:Default:dashboard }

votepage:
    path:    /vote
    defaults: {  _controller: WCSWildExchangeBundle:Question:Vote }

profilpage:
        path:     /profil/{id}
        defaults: {  _controller: WCSWildExchangeBundle:Default:profil }

dashboardformpage:
        path:     /dashboardform
        defaults: {  _controller: WCSWildExchangeBundle:Registration:editprofil}

